language: php
php:
  - 5.6
cache:
  directories:
  - ~/.composer/cache
before_install:
  - composer self-update
install:
  - composer clear-cache
  - composer install --prefer-source
script:
  - ./vendor/bin/phpcs --standard=psr2 src/
  - ./vendor/bin/phpunit --verbose --coverage-clover ./build/logs/clover.xml tests/